# Generated by Django 4.2.13 on 2024-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='meter_type',
            field=models.CharField(choices=[('factory', 'Заводской'), ('water', 'Водяной')], default='factory', max_length=10),
        ),
    ]
