# Generated by Django 4.2.13 on 2024-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reading_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reading',
            name='reading_value',
            field=models.CharField(max_length=30),
        ),
    ]
